version: "3"
services:
    api:
        build: .
        ports:
            - "8000:8000"
        environment:
            - OPENAI_API_BASE=http://localhost:8000/v1
            - OPENAI_API_KEY=sk-xxx
        volumes:
            - ~/.cache/huggingface:/root/.cache/huggingface

    webui:
        image: ghcr.io/open-webui/open-webui:main
        ports:
            - "8080:8080"
        environment:
            - OPENAI_API_BASE=http://api:8000/v1
            - OPENAI_API_KEY=sk-xxx
        depends_on:
            - api
