name: tfmllmserv
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - pip:
    - fastapi
    - uvicorn
    - pydantic
    - pillow
    - transformers
    - timm 